services:
  - type: web
    name: compie-bot
    env: python
    buildCommand: pip uninstall -y telegram & pip install --no-cache-dir --force-reinstall -r requirements.txt
    startCommand: python main.py
    plan: free
